---
# Demo Config
homiemonitor:
  title: Homie Network Monitor
  runmode: demo
  version: 0.5.1

  datasources: 
    dataStorage: ./dataDB/dataDir/devices.db
    demoSource: ./dataDB/demoData/mosquitto.log
    firmwareStorage: ./dataDB/firmwares
    demoNetworks:
    - sknSensors
    - homie




