---
# Demo Config
homiemonitor:
  title: Homie Network Monitor
  runmode: demo
  version: 0.4.0

  datasources: 
    dataStorage: ./dataDB/dataDir/devices.db
    demoSource: ./dataDB/demoData/mosquitto.log
    demoNetworks:
    - sknSensors
    - homie




