---
# Test Mode
homiemonitor:
  title: Homie Network Monitor
  runmode: test # live, demo, test
  version: 0.5.1

  datasources: 
    dataStorage: ./dataDB/dataDir/storage_test.db
    demoSource: ../../dataDB/testData/mosquitto_test.log
    firmwareStorage: ./dataDB/firmwares
    demoNetworks:
    - sknSensors
    - homie

  mqtt:
    clientid: homie-monitor
    broker: ""
    port: 1883
    username: <mqtt-username>
    userpassword: <mqtt-password>
    homiediscoverytopic: "+/+/$name"
    homiesubscriptiontopic: "sknSensors/#"
    lwttopic: sknSensors/$broadcast/LWT
    lwtmsg: HomieMonitor Offline!
